version: 2

jobs:
  build:
    docker:
      - image: jixone/rust-ci:master
    steps:
      - checkout
      - run: |
          cargo build --verbose --all --all-targets
          python3 .circleci/save_binaries.py
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - bins/*
            - tests/*

  test:
    docker:
      - image: jixone/rust-ci:master
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: kcov coverage --include-path=varisat/src /tmp/workspace/tests/varisat/varisat
      - run: bash <(curl -s https://codecov.io/bash)

  build_dev_docs:
    docker:
      - image: jixone/rust-ci:master
    steps:
      - checkout
      - run: |
          cargo +nightly doc --document-private-items --no-deps --all --exclude varisat-cli
          mkdir -p /tmp/workspace
          cp -r target/doc /tmp/workspace/dev_docs
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dev_docs/*

  deploy:
    docker:
      - image: jixone/rust-ci:master
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          if [ $CIRCLE_BRANCH == staging ]; then
            bash .circleci/publish_dev_docs.sh /tmp/workspace/dev_docs git@github.com:jix/varisat.git
          fi

  build_static_linux:
    docker:
      - image: jixone/rust-ci:master
    steps:
      - checkout
      - run: |
          sed -i -e '/^debug = true/d' Cargo.toml
          cargo build --target x86_64-unknown-linux-musl -p varisat-cli --release
          mkdir varisat-linux
          cp target/x86_64-unknown-linux-musl/release/varisat varisat-linux
          tar czf varisat-linux.tar.gz varisat-linux
      - store_artifacts:
          path: varisat-linux.tar.gz
          destination: varisat-linux.tar.gz

  build_static_windows:
    docker:
      - image: jixone/rust-ci:master
    steps:
      - checkout
      - run: |
          sed -i -e '/^debug = true/d' Cargo.toml
          cargo build --target x86_64-pc-windows-gnu -p varisat-cli --release
          mkdir varisat-windows
          cp target/x86_64-pc-windows-gnu/release/varisat.exe .
          zip varisat-windows.zip varisat.exe
      - store_artifacts:
          path: varisat-windows.zip
          destination: varisat-windows.zip

bors_branches: &bors_branches
  filters:
    branches:
      only: [staging, trying]

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          <<: *bors_branches
      - test:
          <<: *bors_branches
          requires: [build]
      - build_dev_docs:
          <<: *bors_branches
      - build_static_linux:
          <<: *bors_branches
      - build_static_windows:
          <<: *bors_branches
      - deploy:
          <<: *bors_branches
          requires:
            - build_dev_docs
            - test
            - build_static_linux
            - build_static_windows
